name: Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r27c
          link-to-sdk: true
          local-cache: true
        
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - run: tree

      - run: chmod +x android/gradlew

      - run: npm install

      - name: Decode Keystore and Setup Signing
        run: |
          echo ${{ secrets.RELEASE_KEYSTORE }} | base64 --decode > android/app/key.keystore
          echo "RELEASE_STORE_FILE=key.keystore" >> android/gradle.properties
          echo "RELEASE_KEY_ALIAS=${{ secrets.RELEASE_KEY_ALIAS }}" >> android/gradle.properties
          echo "RELEASE_STORE_PASSWORD=${{ secrets.RELEASE_STORE_PASSWORD }}" >> android/gradle.properties
          echo "RELEASE_KEY_PASSWORD=${{ secrets.RELEASE_KEY_PASSWORD }}" >> android/gradle.properties

      - run: |
          cd android
          ./gradlew assembleRelease

      - uses: actions/upload-artifact@v4
        with:
          path: android/app/build/outputs/apk/release/app-release.apk